version: '3'

services:

  db:
    container_name: db
    image: postgres:9.6
    restart: always
    volumes:
      - "database:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=SUPERSECRET

volumes:
  database:

