version: '3'

services:

  db:
    container_name: db
    image: postgres:9.6
    restart: always  
    volumes:
      - "database:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=SUPERSECRET 
    networks:
      - metabase

  metabase:
    container_name: metabase-app
    image: metabase/metabase:latest
    build: .
    restart: always 
    volumes:
      - "metabase-data:/metabase-data"
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=SUPERSECRET
      - MB_DB_HOST=db
    networks:
      - metabase

networks:
  metabase:
    driver: bridge

volumes:
  database:
  metabase-data: